### ISSUE TITLE
[Submission]: zKlash

### ISSUE THREAD

**Issue by tarrencev** [dojoengine/game-jams#36]
# zKlash

### Project Summary
> Give a short summary of your game project.

Autobattler where you buy creatures and improve them to defeat waves of enemies

### GitHub
> Provide the GitHub where your project is hosted. Please ensure your github repo is registered with [OnlyDust](https://app.onlydust.com/p/create) to receive awards.

https://github.com/z-korp/zklash

### Play
> Provide instructions on how to play your game. It could be a URL, a README, or a link to a binary to install.

- Play now on: https://zklash-seven.vercel.app/
- How to play video: https://www.youtube.com/watch?v=6wtSFphFvfw

### Twitter
> Provide the projects twitter handle. Please share your submission on socials too for more exposure!

https://twitter.com/zKorp_

### Team members
> Provide a list of your team members.

- Cosmos
  - Github: https://github.com/ClanCo
- Cheelax
  - Github: https://github.com/Cheelax
- ProvableMat
  - Github: https://github.com/Matth26
- Bal7hazar
  - Github: https://github.com/Bal7hazar

### Submission Tracks
> Provide a list of the tracks your project is submitting to. Provide each track on a new line.

Road to Mainnet
New World
Unity SDK

**Comment by guha-rahul** [comment]
hey , why is it giving me a memory out of bounds?
