### ISSUE TITLE
[Team Registration]: Le Olde Fountain

### ISSUE THREAD

**Issue by JacobCWBillings** [dojoengine/game-jams#4]
### Idea Summary

I'm new to this community, and bring a game idea. It revolves around a simple mechanic that inspires some interesting tokenomic incentives and interaction graphs. 

The game is loosely called "Blasphemy!" People can upload user-generated content to a public ledger. Anyone can call "blasphemy!" on content to burn tokens and remove content from the ledger. The goal is to keep content on the ledger (as there can be explicit rewards).  

I really like how this game reveals trends in how certain content is viewed by a community of users. These trends are revealed precisely because the game-state data includes a sparse user-content interaction graph. 

The game interface might look something like a simplified imgur-like, tinder-esque, front end. Sample visualizations of observed trends should also be made available via a suite of data visualization tools.

Re tokenomics: I like how the game allows to modify the value of the costs associated with adding/removing (/tagging?/amplifying?) content in order to adjust the incentives for participating in the game.

### Background

My background is primarily physical science research (computational neuroscience). More recently, I've stepped away from that line of work, and am looking to directly help resolve the metacrisis. I see gamification as a great way to test real world mechanics. If the game is intrinsically social, the game may more directly affect real world issues. 

"Blasphemy!" was inspired during Metafest 2023 as a means of reducing the number of memes (ideas) having any potential to resolve the metacrisis. Consider: the space of all ideas is very large. Too large to think about. A smaller subset of that space contains all *mutually non-blasphemous memes. At least some of those non-blasphemous memes might be useful to resolve the metacrisis.

### Looking for Members

This team is open to additional group members.

Jacob's background is most applicable to the interaction-network visualization aspect of the game. But the rest of it should be doable, right?

**Comment by Jonatan-Chaverri** [comment]
Hi Jacob, 
I'm a Rust developer, looking for a team! This idea seems promising! Let me know and we can chat more! I'm on Discord as jonatanchaverri

**Comment by JacobCWBillings** [comment]
> Hi Jacob, I'm a Rust developer, looking for a team! This idea seems promising! Let me know and we can chat more! I'm on Discord as jonatanchaverri

Perfect timing, Jonatan! I was just about to start on the Vue front end. Will save that for tomorrow, and continue with the dojo dapp, for now.

**Comment by JacobCWBillings** [comment]
Woefully under-prepared for the jam. Will try again on a latter date.
