### ISSUE TITLE
[Submission]: AbyssX

### ISSUE THREAD

**Issue by tarrencev** [dojoengine/game-jams#44]
# AbyssX

### Project Summary
> Give a short summary of your game project.

In a world where every corner has been explored, the only remaining mystery is the great abyss known as "X". Its depths extending into the unknown. In this vast, bottomless vertical cavern, dwell peculiar and wondrous creatures, and slumber precious idols beyond the craftsmanship of modern humanity. The allure of Abyss X's inexplicable existence draws adventurers to embark on a journey into its depths. Players take on the role of adventurers descending deeper into the vast abyssal cavern, confronting unknown and dangerous creatures, and harvesting mysterious treasures. Along the way, they acquire various skills, abilities, and blessings to strengthen themselves. Faced with irresistible temptations and irreversible curses, adventurers can only forge ahead, reaching the deepest depths to uncover the true secrets of the abyss.

### GitHub
> Provide the GitHub where your project is hosted. Please ensure your github repo is registered with [OnlyDust](https://app.onlydust.com/p/create) to receive awards.

[AbyssXDemo](https://github.com/mcjkn007/AbyssXDemo)

### Play
> Provide instructions on how to play your game. It could be a URL, a README, or a link to a binary to install.

[Gameplay Video](https://www.youtube.com/watch?v=j8g6KALxocc)

### Twitter
> Provide the projects twitter handle. Please share your submission on socials too for more exposure!

[mcjkn007](https://twitter.com/mcjkn007)

### Team members
> Provide a list of your team members.

midasX:  
discords:midasx0322  

Lettie Clarke:  
discords:0b1f5cc3

### Submission Tracks
> Provide a list of the tracks your project is submitting to. Provide each track on a new line.

Unity  
New World

**Comment by tarrencev** [comment]
@mcjkn007 the concept here is really cool. The code / video look great. Do you have a more easily playable version I could check out? Perhaps a webgl version similar to what Blob Arena provided in their github readme?

**Comment by mcjkn007** [comment]
> @mcjkn007 the concept here is really cool. The code / video look great. Do you have a more easily playable version I could check out? Perhaps a webgl version similar to what Blob Arena provided in their github readme?

Certainly, sir, I will deploy a playable demo for you to check out as quickly as possible. May I ask if you could allow me 1-2 days for this? I need some time to make a few adjustments on my end, and I am very sorry for any inconvenience this may cause.

**Comment by mcjkn007** [comment]
> @mcjkn007 the concept here is really cool. The code / video look great. Do you have a more easily playable version I could check out? Perhaps a webgl version similar to what Blob Arena provided in their github readme?

I'm very sorry, sir. My colleague on the client side needs to delay the demo for a few days due to personal reasons. We will get it to you by April 20th at the latest

**Comment by mcjkn007** [comment]
> @mcjkn007 the concept here is really cool. The code / video look great. Do you have a more easily playable version I could check out? Perhaps a webgl version similar to what Blob Arena provided in their github readme?

hello sir,the game link is https://clever-internally-antelope.ngrok-free.app
